import { Map } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { EmptyState } from "../components/EmptyState";
import { GlassCard } from "../components/GlassCard";
import { activityApi, documentApi, roadmapApi } from "../../services/api";

export default function LearningRoadmap() {
  const [documents, setDocuments] = useState<any[]>([]);
  const [selectedDocumentId, setSelectedDocumentId] = useState("");
  const [roadmap, setRoadmap] = useState<any | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isRegenerating, setIsRegenerating] = useState(false);

  useEffect(() => {
    const loadDocuments = async () => {
      try {
        const docs = await documentApi.getDocuments();
        setDocuments(docs || []);
        if (docs?.length) {
          setSelectedDocumentId(docs[0]._id);
        }
      } catch (error) {
        toast.error("Failed to load documents");
      } finally {
        setIsLoading(false);
      }
    };

    loadDocuments();
  }, []);

  useEffect(() => {
    if (!selectedDocumentId) {
      setRoadmap(null);
      return;
    }

    const loadRoadmap = async () => {
      try {
        const data = await roadmapApi.getRoadmap(selectedDocumentId);
        setRoadmap(data);
        await activityApi.track({
          type: "roadmap-progress",
          title: "Roadmap opened",
          description: "A learning roadmap was viewed.",
          documentId: selectedDocumentId,
          metadata: {
            roadmapId: data?._id || null,
            itemCount: data?.items?.length || 0,
          },
        });
      } catch (error) {
        setRoadmap(null);
      }
    };

    loadRoadmap();
  }, [selectedDocumentId]);

  const handleRegenerate = async () => {
    if (!selectedDocumentId) {
      return;
    }

    try {
      setIsRegenerating(true);
      const data = await roadmapApi.regenerateRoadmap(selectedDocumentId, "frontend-refresh");
      setRoadmap(data);
      toast.success("Roadmap regenerated");
    } catch (error: any) {
      toast.error(error?.response?.data?.message || "Failed to regenerate roadmap");
    } finally {
      setIsRegenerating(false);
    }
  };

  if (!isLoading && documents.length === 0) {
    return (
      <EmptyState
        icon={Map}
        title="No documents available"
        description="Upload a document first to generate a learning roadmap."
      />
    );
  }

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      <div className="flex items-center justify-between gap-4">
        <div>
          <h1 className="text-4xl font-bold text-[var(--foreground)] mb-2">Learning Roadmap</h1>
          <p className="text-[var(--muted-foreground)] text-lg">A document-specific ordered plan generated by the backend.</p>
        </div>
        <button
          onClick={handleRegenerate}
          disabled={!selectedDocumentId || isRegenerating}
          className="px-4 py-3 bg-gradient-to-r from-[var(--accent-primary)] to-[var(--accent-secondary)] text-white rounded-2xl disabled:opacity-60"
        >
          {isRegenerating ? "Regenerating..." : "Regenerate"}
        </button>
      </div>

      <GlassCard className="p-6">
        <label className="block text-sm text-[var(--muted-foreground)] mb-2">Document</label>
        <select
          value={selectedDocumentId}
          onChange={(event) => setSelectedDocumentId(event.target.value)}
          className="w-full max-w-xl px-4 py-3 bg-[var(--secondary)]/50 border border-[var(--border)] rounded-2xl text-[var(--foreground)]"
        >
          {documents.map((document) => (
            <option key={document._id} value={document._id}>
              {document.title}
            </option>
          ))}
        </select>
      </GlassCard>

      {roadmap?.items?.length ? (
        <div className="space-y-4">
          {roadmap.items.map((item: any) => (
            <GlassCard key={`${item.order}-${item.concept?._id || item.order}`} className="p-6">
              <div className="flex items-start gap-4">
                <div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-[var(--accent-primary)] to-[var(--accent-secondary)] text-white flex items-center justify-center">
                  {item.order}
                </div>
                <div className="flex-1">
                  <div className="text-xl font-semibold text-[var(--foreground)]">{item.concept?.name || "Concept"}</div>
                  <div className="text-sm text-[var(--muted-foreground)] mt-2">{item.reason}</div>
                  <div className="text-sm text-[var(--muted-foreground)] mt-2">Estimated time: {item.estimatedMinutes} minutes</div>
                  <div className="flex flex-wrap gap-2 mt-4">
                    {(item.recommendedResources || []).map((resource: any, index: number) => (
                      <span
                        key={`${resource.label}-${index}`}
                        className="px-3 py-1 rounded-full bg-[var(--secondary)] text-[var(--foreground)] text-sm border border-[var(--border)]"
                      >
                        {resource.label}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </GlassCard>
          ))}
        </div>
      ) : (
        <GlassCard className="p-12 text-center text-[var(--muted-foreground)]">
          No roadmap is available for this document yet.
        </GlassCard>
      )}
    </div>
  );
}
